### ISSUE TITLE
Python 2 and 3

### ISSUE THREAD

**Issue by sipv** [maedoc/tvb-make#30]
`create_tvb_dataset.py` requires Python 3.6, while TVB runs on Python 2. Thus we need to have separate environments for these, and to add some switching to the appropriate one.

**Comment by maedoc** [comment]
we won't be shipping the framework, and we're going to move TVB to Py 3 (cf [`py3` branch](https://github.com/the-virtual-brain/tvb-library/tree/py3)), so maybe it'd be easier to just have a Py 3 environment using the `py3` branch of TVB? I'm pretty sure the rest of the python libs we use are ok on Py 3

**Comment by maedoc** [comment]
Rebuilding the image with Py3 conda environment went fine, so I'm pushing that now and closing this
