### ISSUE TITLE
Xyz centers for aparc & label files

### ISSUE THREAD

**Issue by maedoc** [maedoc/tvb-make#5]
Labelconfig step could permute the order of anatomical nodes, so it'd be good to produce xyz center files for `aparc+*.mgz` and `label*.mif` used for connectivity.

**Comment by sipv** [comment]
If I understand your concern correctly, it should be alright now - the python script that generates tvb-compatible connectivity zip file does the same permutation as labelconvert:

https://github.com/maedoc/tvb-make/blob/tvb-files/create_tvb_dataset.py#L380

**Comment by maedoc** [comment]
Ah, yes, excellent.  Good job on that btw, that's not fun code to write..

**Comment by sipv** [comment]
> not fun

I disagree. Anyway, it was mostly cleaning up old Tim's code. Furthermore, the code should be reviewed if we start using non-default parcellations - there are some hardcoded values that can mess things up.
